apiVersion: v1
kind: Service
metadata:
  name: archburgers-svc-catalogo-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-name: k8s-cluster-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: archburgers-svc-catalogo
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
